### ISSUE TITLE
Pchan crash breaking a hot air balloon in Creative

### ISSUE THREAD

**Issue by keenerb** [GotoLink/pchan3#2]
Forge 1307, SSP.

Breaking an airship generates the following error:

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/18/15 1:15 PM
Description: Ticking Particle

java.lang.NullPointerException: Ticking Particle
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:600)
	at net.minecraft.client.particle.EntityFX.func_70071_h_(SourceFile:117)
	at assets.pchan3.EntitySteamExplode.func_70071_h_(EntitySteamExplode.java:25)
	at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:77)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2044)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by keenerb** [comment]
You're the best Gotolink
